DROP TABLE IF EXISTS `SYS_PROCESS_DEFINITION`;
CREATE  TABLE IF NOT EXISTS `SYS_PROCESS_DEFINITION` (
	`ID` 								BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT ,
	`NAME`								VARCHAR(100) NOT NULL ,
	`VERSION` 							VARCHAR(4) 	NOT NULL ,
	`XML`								LONGTEXT NOT NULL,
	`CREATED_DATE` 						DATETIME NOT NULL,
	`CREATED_BY` 						VARCHAR(100) NOT NULL ,
	`UPDATED_DATE` 						DATETIME NULL DEFAULT NULL,
	`UPDATED_BY` 						VARCHAR(100) DEFAULT NULL , 
  PRIMARY KEY (`ID`), INDEX SYS_PROCESS_DEFINITION_NAME_VERSION (NAME,VERSION))
ENGINE = InnoDB;


DROP TABLE IF EXISTS `SYS_TASK_EXECUTION_LOGS`;
CREATE  TABLE IF NOT EXISTS `SYS_TASK_EXECUTION_LOGS` (
	`ID` 								BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT ,
	`REQUEST_ID`						VARCHAR(200) NOT NULL ,
	`CURRENT_TASK` 						VARCHAR(100) NOT NULL ,
	`NEXT_TASK`							VARCHAR(100) NOT NULL,
	`TASK_STATUS`						VARCHAR(2) NOT NULL,
	`CREATED_DATE` 						DATETIME NOT NULL,
	`CREATED_BY` 						VARCHAR(100) NOT NULL ,
	`UPDATED_DATE` 						DATETIME NULL DEFAULT NULL,
	`UPDATED_BY` 						VARCHAR(100) DEFAULT NULL , 
  PRIMARY KEY (`ID`), INDEX SYS_TASK_EXECUTION_LOGS_REQUEST_ID_CT (REQUEST_ID, CURRENT_TASK), 
					  INDEX	SYS_TASK_EXECUTION_LOGS_REQUEST_ID_NT_STATUS (REQUEST_ID, NEXT_TASK, TASK_STATUS))
ENGINE = InnoDB;


DROP TABLE IF EXISTS `SYS_API_KEY_VERSION_MAPPING`;
CREATE  TABLE IF NOT EXISTS `SYS_API_KEY_VERSION_MAPPING` (
	`ID` 								BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT ,
	`API_KEY`							VARCHAR(200) NOT NULL ,
	`API_VERSION` 						VARCHAR(10) NOT NULL ,
	`CREATED_DATE` 						DATETIME NOT NULL,
	`CREATED_BY` 						VARCHAR(100) NOT NULL ,
	`UPDATED_DATE` 						DATETIME NULL DEFAULT NULL,
	`UPDATED_BY` 						VARCHAR(100) DEFAULT NULL , 
  PRIMARY KEY (`ID`), INDEX SYS_API_KEY_VERSION_MAPPING_API_KEY_VERSION (API_KEY, API_VERSION))
ENGINE = InnoDB;
