
package org.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * WineDirect Web Services for the Direct-to-Consumer (DTC) Fulfillment System
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "dtc", targetNamespace = "http://winedirect.com/4/0/dtc/", wsdlLocation = "http://webservices-test.winedirect.com/4/0/dtc.asmx?WSDL")
public class Dtc
    extends Service
{

    private final static URL DTC_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.ws.client.Dtc.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.ws.client.Dtc.class.getResource(".");
            url = new URL(baseUrl, "http://webservices-test.winedirect.com/4/0/dtc.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://webservices-test.winedirect.com/4/0/dtc.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DTC_WSDL_LOCATION = url;
    }

    public Dtc(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Dtc() {
        super(DTC_WSDL_LOCATION, new QName("http://winedirect.com/4/0/dtc/", "dtc"));
    }

    /**
     * 
     * @return
     *     returns DtcSoap
     */
    @WebEndpoint(name = "dtcSoap")
    public DtcSoap getDtcSoap() {
        return super.getPort(new QName("http://winedirect.com/4/0/dtc/", "dtcSoap"), DtcSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DtcSoap
     */
    @WebEndpoint(name = "dtcSoap")
    public DtcSoap getDtcSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://winedirect.com/4/0/dtc/", "dtcSoap"), DtcSoap.class, features);
    }

}
