
package org.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "dtcSoap", targetNamespace = "http://winedirect.com/4/0/dtc/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DtcSoap {


    /**
     * 
     * @param checkSystemStatusRequest
     * @return
     *     returns org.ws.client.CheckSystemStatusResponse2
     */
    @WebMethod(operationName = "CheckSystemStatus", action = "http://winedirect.com/4/0/dtc/CheckSystemStatus")
    @WebResult(name = "CheckSystemStatusResult", targetNamespace = "http://winedirect.com/4/0/dtc/")
    @RequestWrapper(localName = "CheckSystemStatus", targetNamespace = "http://winedirect.com/4/0/dtc/", className = "org.ws.client.CheckSystemStatus")
    @ResponseWrapper(localName = "CheckSystemStatusResponse", targetNamespace = "http://winedirect.com/4/0/dtc/", className = "org.ws.client.CheckSystemStatusResponse")
    public CheckSystemStatusResponse2 checkSystemStatus(
        @WebParam(name = "CheckSystemStatusRequest", targetNamespace = "http://winedirect.com/4/0/dtc/")
        CheckSystemStatusRequest checkSystemStatusRequest);

    /**
     * 
     * @param submitOrdersRequest
     * @return
     *     returns org.ws.client.SubmitOrdersResponse2
     */
    @WebMethod(operationName = "SubmitOrders", action = "http://winedirect.com/4/0/dtc/SubmitOrders")
    @WebResult(name = "SubmitOrdersResult", targetNamespace = "http://winedirect.com/4/0/dtc/")
    @RequestWrapper(localName = "SubmitOrders", targetNamespace = "http://winedirect.com/4/0/dtc/", className = "org.ws.client.SubmitOrders")
    @ResponseWrapper(localName = "SubmitOrdersResponse", targetNamespace = "http://winedirect.com/4/0/dtc/", className = "org.ws.client.SubmitOrdersResponse")
    public SubmitOrdersResponse2 submitOrders(
        @WebParam(name = "SubmitOrdersRequest", targetNamespace = "http://winedirect.com/4/0/dtc/")
        SubmitOrdersRequest submitOrdersRequest);

    /**
     * Cancels an order withing the fulfillment database. The cancellation will only succeed if the operational requirements for cancellation are met. Namely, the order should not be in the WMS system. If it is, then the order cannot have been released for picking.
     * 
     * @param cancelOrderRequest
     * @return
     *     returns org.ws.client.CancelOrderResponse2
     */
    @WebMethod(operationName = "CancelOrder", action = "http://winedirect.com/4/0/dtc/CancelOrder")
    @WebResult(name = "CancelOrderResult", targetNamespace = "http://winedirect.com/4/0/dtc/")
    @RequestWrapper(localName = "CancelOrder", targetNamespace = "http://winedirect.com/4/0/dtc/", className = "org.ws.client.CancelOrder")
    @ResponseWrapper(localName = "CancelOrderResponse", targetNamespace = "http://winedirect.com/4/0/dtc/", className = "org.ws.client.CancelOrderResponse")
    public CancelOrderResponse2 cancelOrder(
        @WebParam(name = "CancelOrderRequest", targetNamespace = "http://winedirect.com/4/0/dtc/")
        CancelOrderRequest cancelOrderRequest);

    /**
     * 
     * @param getOrderStatusRequest
     * @return
     *     returns org.ws.client.GetOrderStatusResponse2
     */
    @WebMethod(operationName = "GetOrderStatus", action = "http://winedirect.com/4/0/dtc/GetOrderStatus")
    @WebResult(name = "GetOrderStatusResult", targetNamespace = "http://winedirect.com/4/0/dtc/")
    @RequestWrapper(localName = "GetOrderStatus", targetNamespace = "http://winedirect.com/4/0/dtc/", className = "org.ws.client.GetOrderStatus")
    @ResponseWrapper(localName = "GetOrderStatusResponse", targetNamespace = "http://winedirect.com/4/0/dtc/", className = "org.ws.client.GetOrderStatusResponse")
    public GetOrderStatusResponse2 getOrderStatus(
        @WebParam(name = "GetOrderStatusRequest", targetNamespace = "http://winedirect.com/4/0/dtc/")
        GetOrderStatusRequest getOrderStatusRequest);

    /**
     * 
     * @param getShipmentsRequest
     * @return
     *     returns org.ws.client.GetShipmentsResponse2
     */
    @WebMethod(operationName = "GetShipments", action = "http://winedirect.com/4/0/dtc/GetShipments")
    @WebResult(name = "GetShipmentsResult", targetNamespace = "http://winedirect.com/4/0/dtc/")
    @RequestWrapper(localName = "GetShipments", targetNamespace = "http://winedirect.com/4/0/dtc/", className = "org.ws.client.GetShipments")
    @ResponseWrapper(localName = "GetShipmentsResponse", targetNamespace = "http://winedirect.com/4/0/dtc/", className = "org.ws.client.GetShipmentsResponse")
    public GetShipmentsResponse2 getShipments(
        @WebParam(name = "GetShipmentsRequest", targetNamespace = "http://winedirect.com/4/0/dtc/")
        GetShipmentsRequest getShipmentsRequest);

    /**
     * 
     * @param getShipmentUpdatesRequest
     * @return
     *     returns org.ws.client.GetShipmentUpdatesResponse2
     */
    @WebMethod(operationName = "GetShipmentUpdates", action = "http://winedirect.com/4/0/dtc/GetShipmentUpdates")
    @WebResult(name = "GetShipmentUpdatesResult", targetNamespace = "http://winedirect.com/4/0/dtc/")
    @RequestWrapper(localName = "GetShipmentUpdates", targetNamespace = "http://winedirect.com/4/0/dtc/", className = "org.ws.client.GetShipmentUpdates")
    @ResponseWrapper(localName = "GetShipmentUpdatesResponse", targetNamespace = "http://winedirect.com/4/0/dtc/", className = "org.ws.client.GetShipmentUpdatesResponse")
    public GetShipmentUpdatesResponse2 getShipmentUpdates(
        @WebParam(name = "GetShipmentUpdatesRequest", targetNamespace = "http://winedirect.com/4/0/dtc/")
        GetShipmentUpdatesRequest getShipmentUpdatesRequest);

    /**
     * 
     * @param getInventoryRequest
     * @return
     *     returns org.ws.client.GetInventoryResponse2
     */
    @WebMethod(operationName = "GetInventory", action = "http://winedirect.com/4/0/dtc/GetInventory")
    @WebResult(name = "GetInventoryResult", targetNamespace = "http://winedirect.com/4/0/dtc/")
    @RequestWrapper(localName = "GetInventory", targetNamespace = "http://winedirect.com/4/0/dtc/", className = "org.ws.client.GetInventory")
    @ResponseWrapper(localName = "GetInventoryResponse", targetNamespace = "http://winedirect.com/4/0/dtc/", className = "org.ws.client.GetInventoryResponse")
    public GetInventoryResponse2 getInventory(
        @WebParam(name = "GetInventoryRequest", targetNamespace = "http://winedirect.com/4/0/dtc/")
        GetInventoryRequest getInventoryRequest);

    /**
     * 
     * @param validateAddressRequest
     * @return
     *     returns org.ws.client.ValidateAddressResponse2
     */
    @WebMethod(operationName = "ValidateAddress", action = "http://winedirect.com/4/0/dtc/ValidateAddress")
    @WebResult(name = "ValidateAddressResult", targetNamespace = "http://winedirect.com/4/0/dtc/")
    @RequestWrapper(localName = "ValidateAddress", targetNamespace = "http://winedirect.com/4/0/dtc/", className = "org.ws.client.ValidateAddress")
    @ResponseWrapper(localName = "ValidateAddressResponse", targetNamespace = "http://winedirect.com/4/0/dtc/", className = "org.ws.client.ValidateAddressResponse")
    public ValidateAddressResponse2 validateAddress(
        @WebParam(name = "ValidateAddressRequest", targetNamespace = "http://winedirect.com/4/0/dtc/")
        ValidateAddressRequest validateAddressRequest);

    /**
     * Retrieve a listing of products sellable by the indicated account number. If a SKU is provided in the request, the search will be limited to the given SKU. Otherwise, the full listing of orderable products will be returned.
     * 
     * @param getProductsRequest
     * @return
     *     returns org.ws.client.GetProductsResponse2
     */
    @WebMethod(operationName = "GetProducts", action = "http://winedirect.com/4/0/dtc/GetProducts")
    @WebResult(name = "GetProductsResult", targetNamespace = "http://winedirect.com/4/0/dtc/")
    @RequestWrapper(localName = "GetProducts", targetNamespace = "http://winedirect.com/4/0/dtc/", className = "org.ws.client.GetProducts")
    @ResponseWrapper(localName = "GetProductsResponse", targetNamespace = "http://winedirect.com/4/0/dtc/", className = "org.ws.client.GetProductsResponse")
    public GetProductsResponse2 getProducts(
        @WebParam(name = "GetProductsRequest", targetNamespace = "http://winedirect.com/4/0/dtc/")
        GetProductsRequest getProductsRequest);

}
