package com.wineaccess.util.notification;

import java.util.Map;

/**
 * Formatter Interface to format a given template with the notification
 * parameters generated by NotificationEmitter. The implementation class can
 * write their your own custom formatter to handle a template.
 */
public interface IMessageFormatter {

	/**
	 * Formats a given message template with the notification event data.
	 * 
	 * @param template -
	 *            String message template for notification
	 * @param notificationAttributes -
	 *            notification attributes which is to be used for template
	 * @return - formatted message
	 */
	public String format(String message, Map<String, String> notificationAttributes);
}
